# Practical 10

**Aim:** Demonstrate NumPy array creation, indexing, slicing, reshaping, broadcasting and mathematical operations on multidimensional arrays.

### 1. Array Creation

In [1]:
import numpy as np

x1 = np.array([3, 6, 9, 12, 15])
x2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("Vector x1:", x1)
print("Matrix x2:\n", x2)

print("Zeros (4x2):\n", np.zeros((4, 2)))
print("Ones (1x5):\n", np.ones((1, 5)))
print("Range (2 to 20 by 2):", np.arange(2, 22, 2))
print("Linspace (0 to 1, 4 steps):", np.linspace(0, 1, 4))
print("Eye Matrix:\n", np.eye(3))

Vector x1: [ 3  6  9 12 15]
Matrix x2:
 [[1 2 3 4]
 [5 6 7 8]]
Zeros (4x2):
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Ones (1x5):
 [[1. 1. 1. 1. 1.]]
Range (2 to 20 by 2): [ 2  4  6  8 10 12 14 16 18 20]
Linspace (0 to 1, 4 steps): [0.         0.33333333 0.66666667 1.        ]
Eye Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2. Indexing and Slicing

In [2]:
sample = np.array([11, 22, 33, 44, 55, 66, 77, 88])
print("Third item:", sample[2])
print("Slice [2:7]:", sample[2:7])
print("Alternate elements:", sample[::2])

block = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nBlock:\n", block)
print("Element (1, 1):", block[1, 1])
print("First 2 rows:\n", block[:2, :])
print("Last 2 columns:\n", block[:, 1:])

Third item: 33
Slice [2:7]: [33 44 55 66 77]
Alternate elements: [11 33 55 77]

Block:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element (1, 1): 5
First 2 rows:
 [[1 2 3]
 [4 5 6]]
Last 2 columns:
 [[2 3]
 [5 6]
 [8 9]]


### 3. Reshaping Array

In [3]:
vec = np.arange(1, 19)
print("Vector length:", len(vec))

mat3x6 = vec.reshape(3, 6)
print("3x6 Form:\n", mat3x6)

print("Flatten array:", mat3x6.flatten())

Vector length: 18
3x6 Form:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
Flatten array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


### 4. Broadcasting

In [4]:
mat = np.array([[100, 200, 300], [400, 500, 600]])
offset = np.array([10, 20, 30])

print("Original:\n", mat)
print("Offset:", offset)
print("Broadcasted Add:\n", mat + offset)
print("Scalar Multiply (* 0.5):\n", mat * 0.5)

Original:
 [[100 200 300]
 [400 500 600]]
Offset: [10 20 30]
Broadcasted Add:
 [[110 220 330]
 [410 520 630]]
Scalar Multiply (* 0.5):
 [[ 50. 100. 150.]
 [200. 250. 300.]]


### 5. Math & Stat Functions

In [5]:
u = np.array([[4, 2], [1, 3]])
v = np.array([[1, 1], [2, 2]])

print("u + v:\n", u + v)
print("u - v:\n", u - v)
print("Matrix Dot Product:\n", np.dot(u, v))

print("Total Sum:", u.sum())
print("Row Mean:", u.mean(axis=1))
print("Col Mean:", u.mean(axis=0))
print("Standard Deviation:", round(u.std(), 2))
print("Square Root:\n", np.sqrt(u))

u + v:
 [[5 3]
 [3 5]]
u - v:
 [[ 3  1]
 [-1  1]]
Matrix Dot Product:
 [[8 8]
 [7 7]]
Total Sum: 10
Row Mean: [3. 2.]
Col Mean: [2.5 2.5]
Standard Deviation: 1.12
Square Root:
 [[2.         1.41421356]
 [1.         1.73205081]]
